version: '2'
services:
    dynastywars-app:
        image: dynastywars
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dynastywars-postgresql:5432/dynastywars
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dynastywars-elasticsearch:9300
        ports:
            - 8084:8084
    dynastywars-postgresql:
        extends:
            file: postgresql.yml
            service: dynastywars-postgresql
    dynastywars-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dynastywars-elasticsearch
